### PR TITLE
Constructing a sparse matrix class in Rcpp

### PR DESCRIPTION
**Pull request by zdebruine**
Here we go... sorry about the other two pulls.

Please advise if any edits would be helpful.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I'll give it a whirl over the weekend.

Next time, stick with one branch and issue ticket.  `git push --force-with-lease` is your friend (on isolated branches).

**Comment by eddelbuettel** [comment]
It is a fine submission but the write-up is rather hurried. I am going over it line by line.

**Comment by eddelbuettel** [comment]
One of the many problems here is that "Reference Class" is already an existing concept in R and means something _completely different_.  Your are apparently still a little unfamiliar with our documentation (understandable, there is simply a lot of it as the subject matter is complex) which generally uses 'proxy object'.

**Comment by eddelbuettel** [comment]
I think this is plainly wrong:

> This is because Rcpp passes from R to C++ by reference, and passes from C++ to R by copy.

**Comment by zdebruine** [comment]
Thanks for catching that!  In benchmarking I see essentially no latency from R to C++, and considerably greater latency from C++ to R for the same structures. Maybe that's something with my system or setup, or the way I'm using chrono and microbenchmark to deduce runtimes, I don't know.

I'll admit to being just a few months new to C++ and Rcpp. Learning from you and others in the Rcpp universe has been invaluable. Let me know if any changes need to be made beyond semantics that you can't readily address.

**Comment by zdebruine** [comment]
Nice, I like it!  Thanks for cleaning it up.

**Comment by eddelbuettel** [comment]
First off, thanks again.  You had a pretty clever insight here that is absolutely worthy of a writeup and package exploring it [1].

Second, congratulations on getting `tags` right.  Very few submissions do.

Thirdly, all this was clearly a little rushed. I just committed one first pass over it (following the obvious correction of putting it in the right directory).   In sum, I think we can post this but maybe take a look at it.   Jekyll can be a beast to set up, and an-hoc rmarkdown render should work for you locally too.  We do have a few stylistic conventions that were off too which I corrected.

Overall still very nice and good to have.  Looking forward to seeing this posted!


[1] Part of me thinks there may be a reason `dgCMatrix` and friends do what they do, and `arma::sp_mat` does what it does. But I can't quite put my finger on it yet.

**Comment by zdebruine** [comment]
Just rendered the markdown and all looks good, I fixed one style issue between "Here we have:" and the bullet list describing slots in the dgCMatrix.

**Comment by eddelbuettel** [comment]
That was because _some_ markdown renderers require an empty line before and/or after bullet lists.  I had been burned there so I tend to add them on purpose.  Jekyll does not care either way so it looks the same:

image

**Comment by eddelbuettel** [comment]
I'll let this sit for a bit but plan to merge (and hence "publish") later.  Fine by you?

**Comment by zdebruine** [comment]
Perfect.

**Comment by zdebruine** [comment]
> [1] Part of me thinks there may be a reason `dgCMatrix` and friends do what they do, and `arma::sp_mat` does what it does. But I can't quite put my finger on it yet.

You may see something I haven't yet seen, but one obvious difference is how values are stored. Eigen (Arma too?) stores each column as an individual sparse vector, permitting efficient insertion of values at zero-valued indices (and deletion of non-zeros) where the pointers only need to be adjusted within the column. In a dgCMatrix, the entire `@p` and `@i` vector needs to be incremented or decremented after the index being manipulated, making it extremely inefficient for large matrices.

**Pull request merged**
