### PR TITLE
add articles showcasing Boost.SIMD usage

### PR DESCRIPTION
**Pull request by kevinushey**
This PR adds two articles, showcasing how `Boost.SIMD` (now part of the development version of `RcppParallel`) can be used.

@jjallaire, can you review?

(Aside -- is there a simple way of building only a subset of gallery articles?)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Re the aside: it'll probably work if you just 'empty' the source directory.  Otherwise I sometimes just deal with the one file in a non-gallery / standard rmarkdown/knitr way.

**Comment by eddelbuettel** [comment]
Reads well (in the .md version). Usual old-man complaints about "don't, can't" versus expanded "do not, cannot" where I prefer the latter.  We could also put this RcppParallel release in a drat, or just wait with the post til the package is updated (presumably soon).

**Comment by kevinushey** [comment]
Thanks @eddelbuettel -- I was doing exactly that when updating (`rm 201[2-5]*`, build, `git reset`). I also updated with a little blurb on the variance article that the comparison is somewhat unfair, as we don't handle `NA` with the same granularity that R does.

**Comment by jjallaire** [comment]
I just updated RcppParallel about a week ago so the update won't be before
3-4 weeks from now. I think it's valuable to do some promotion beforehand
to work out kinks and get feedback so I'd be in favor of posting soon.

On Thu, Jan 21, 2016 at 3:04 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
And maybe if we remember to update the article to (then) just recommend installation from CRAN...

**Comment by kevinushey** [comment]
I've also added a little `staging/` folder to make iteration a bit easier. The idea is that you can work / iterate on new articles in that folder, then just run `make` to copy the article to the `src/` directory, and also build the corresponding article.

**Comment by jjallaire** [comment]
Since these will currently the the only documentation for Boost.SIMD we should probably add one more high level article which will be a general orientation with light examples, and which will also include information on how to include Boost.SIMD in a package (and how to conditionally compile for SIMD to maintain platform compatibility). It could basically be an iteration of this article: https://github.com/RcppCore/RcppParallel/blob/master/examples/simd-operations.Rmd

Then the other two articles could link to it at the appropriate places.

**Comment by jjallaire** [comment]
If you decide to keep the "examples/" folder in the package you might want
to link from the overview post to that folder (and then also link to the
other gallery articles once they are posted).

**Comment by kevinushey** [comment]
I think I'll produce one more article on how we can handle NAs (ie, investigating the bitmask stuff we discussed before, re: Wizard). This might also encourage us to add some facilities for generating NA bitmasks in `RcppParallel` as well.

It don't think it will be faster than the case where we just propagate NAs, but might give a meaningful speed bump versus the 'scalar' way of omitting NAs.

**Comment by jjallaire** [comment]
Okay, I also think we need the "overview" article which is basically an
adaptation of the original article you had in the examples folder.

**Comment by kevinushey** [comment]
Yep, I've added that as well (sorry, I've been force pushing on this repo so the changes haven't been as visible).

Article: https://raw.githubusercontent.com/kevinushey/rcpp-gallery/5ed7f381a727dffb3d6821c9e507a0041f58ba77/_posts/2016-01-22-simd-introduction.md

**Comment by jjallaire** [comment]
Okay, excellent. Looks great!

**Comment by jjallaire** [comment]
If we haven't already we should cross link the various articles. The
overview article should link to the other 3 for sure and the examples
should link to the main article at the bottom.

**Comment by kevinushey** [comment]
I've bumped this once more, retaining the same three articles but updating them in a couple ways:
- Using RcppNT2 instead of RcppParallel as we've moved the code to a separate package,
- We refer to **NT<sup>2</sup>** as a collection of libraries: NT2 itself, Boost.Dispatch and Boost.SIMD. We use this to make things a bit more clear (e.g. NT2 uses Boost.SIMD under the hood to enable SIMD optimziations)
- The introduction article is trimmed a bit, and links to our [GitHub page](https://rcppcore.github.io/RcppNT2/) for more information.

Let me know what you think.

**Comment by eddelbuettel** [comment]
Do you think this should get relased before RcppNT2 is on CRAN?

**Comment by kevinushey** [comment]
I think yes, just so we can advertise the package a bit and get some users before our first CRAN submission -- that way, we can tweak / tidy things up before we submit to CRAN if required. Let's see what @jjallaire thinks, though.

**Comment by jjallaire** [comment]
Yes, I agree that we want to get some usage / feedback under our belt
before submitting to CRAN. I'd be okay merging these now unless @kevinushey
wants to add some more to the documentation on the website first. Once they
are published I'd also cross-link to these articles from the website.

**Comment by jjallaire** [comment]
Actually, we should also mention on the website that users should get the
RStudio Preview release if they are using RStudio for their Rcpp
development (Dirk, this is because NT2's expression templates crush
libclang to the point of unsuitability -- the preview release works around
this by shutting off libclang when NT2 is in the picture).

**Comment by kevinushey** [comment]
Mentioned RStudio preview here now: https://github.com/RcppCore/RcppNT2/commit/4c9052403de8fa9154a9aad3652bd7f2b175edbf

@jjallaire, I'm fine with merging these articles as is (I've been updating the documentation on the website and I think it's in good shape). Once the gallery articles are up I can link to those as well.

**Comment by jjallaire** [comment]
@eddelbuettel Are you okay with merging sooner rather than later?

**Comment by eddelbuettel** [comment]
Yup. Done.

**Comment by eddelbuettel** [comment]
Seems to have added six in `src/` but three in `_posts/` -- do we need to clean up some more?

**Comment by kevinushey** [comment]
Sorry, those 2016 articles with `-simd-` in the name are old and snuck in. I'll clear them out.

**Comment by kevinushey** [comment]
(PS: Thanks for reviewing! Super excited to have RcppNT2 up and running with a few examples; hopefully we'll see a couple early adopters give it a shot.)

**Pull request merged**
