### PR TITLE
Commit for the rcpp gallery article on Nullable

### PR DESCRIPTION
**Pull request by sn248**
Dirk

Please find the source for Rcpp Gallery article for Nullable. Please feel free to edit as you please.

Best
Satya

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Perfect. I'll compare with the earlier draft, make adjustments to the header and then push back here into your branch for you to review -- ok?

**Comment by sn248** [comment]
Sounds perfect!

**Comment by eddelbuettel** [comment]
Ok, just pushed it back to you.  Really tiny changes (path, filename, header, small whitespace and indentation changes).  No changes to content which was good!

Lemme know if thies flies and I'll merge.

**Comment by sn248** [comment]
The minor edits look good! Please feel free to merge and publish. Thanks again for the opportunity!

**Pull request merged**
