### PR TITLE
add sir post

### PR DESCRIPTION
**Pull request by olmjo**
- add post on SIR for probability params in binomial model
- demos figures
- demos update of RcppArmadillo::sample and RcppArmadillo::FixProb

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Rocking!

**Comment by eddelbuettel** [comment]
Looks like it wants the unreleased RcppArmadillo ...

**Comment by eddelbuettel** [comment]
But:

``` bash
edd@don:~/git/rcpp-gallery(gh-pages)$ make preview
make -C src
make[1]: Entering directory `/home/edd/git/rcpp-gallery/src'
make[1]: `all' is up to date.
make[1]: Leaving directory `/home/edd/git/rcpp-gallery/src'
cp figure/* articles/figure/
cp: cannot stat ‘figure/*’: No such file or directory
make: *** [knit] Error 1
edd@don:~/git/rcpp-gallery(gh-pages)$ 
```

**Comment by eddelbuettel** [comment]
Followed by 

``` bash
[1] "../_posts/2014-10-23-SIR-and-revolution.md"
make[1]: Leaving directory `/home/edd/git/rcpp-gallery/src'
cp figure/* articles/figure/
cp: cannot create regular file ‘articles/figure/’: No such file or directory
make: *** [knit] Error 1
```

**Comment by olmjo** [comment]
Sorry forgot to mention that in the pr. Needs the gh version. Happy to let
it sit as a pr until it's on cran if that's what you want.

**Comment by eddelbuettel** [comment]
No that is ok [as we "just" push processed .md file GH ]  -- but my rcpp-gallery checkout seems out of sync.  Do I need new directories and/or new jekyll / ruby tools?  What is directory articles/ ?

**Pull request merged**
