### PR TITLE
Added Custom Templated As & Wrap

### PR DESCRIPTION
**Pull request by coatless**
Per:

http://stackoverflow.com/questions/37935177/convert-rcpp-numeric-vector-into-boostublasvector

I think the spaces are also done properly this time.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
May add tag `vector` etc pp -- will try to give it one look over but so far so good :)

**Comment by dcdillon** [comment]
@coatless there is a (rather new and not quite complete, but useful) way to convert from the `Rcpp` type to a C type without going through the RTYPE to ctype mappings.  It is available [here](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/algorithm.h#L81-L135).

Basically this defines two `type_traits` like things that I needed for algorithms (specifically what I needed was to be able to deduce the C type given simply an iterator from Rcpp).  They are called `Rcpp::algorithm::helpers::ctype` and `Rcpp::algorithm::helpers::decays_to_ctype`.  Essentially they work together to tell you a) whether a type can be cast to a C++ numeric type and b) which one is the best fit.  You may find that useful.

**Comment by eddelbuettel** [comment]
(Told @dcdillon to post here as he has too little karma to post on SO :grimacing: ...)

**Comment by coatless** [comment]
@dcdillon  This is exactly what I wanted to know earlier!  I spent a lot of time looking under `Rcpp::traits` for such a feature (and a few other headers). I even made a note to revisit & question:

Last paragraph of SO response:

> In other news, I think what probably stopped you from being able to create the alternate template function above (e.g. rcpp2ublas) was not being able to deduce what C++ T type the Rcpp::Vector was. Personally, after digging around in the Rcpp GitHub Repo, I'm not sure such a conversion index exists or if it does should be used due to the Shield usage. Digging deeper into conversions is an adventure for another day.

& Follow up to Dirk:

> Sure! Out of pure curiosity there is no mapping from Rtype to Cpp type?

**Is there any reason why the conversion from Rcpp to Ctype is underneath `Rcpp::algorithm` instead of `Rcpp::traits`?**

**Comment by coatless** [comment]
Seems like the last question was just answered by a post in-progress to the gallery by you (@dcdillon) ! Thanks for 1. the overview on the algorithm functionality and 2. developing it.

**Comment by eddelbuettel** [comment]
Very nice post, just did one minor pass over it.  

Maybe add a paragraph pointing to the @dcdillon piece?

**Comment by coatless** [comment]
@eddelbuettel 

Definitely.

Could probably show how to do it w/o the `as<>()` and `wrap()` add a non-rcpp template example. Also, I've meant to ask you this, but:
1. What is the spacing custom? 5 in?
2. The lines seem to be trimmed. What is the character/width & was it automatic or just by manual return?

**Comment by eddelbuettel** [comment]
I just use basic Emacs C++ and R styles (as in my .emacs).  That is basically
- 4 spaces rather than the 2 spaces from RStudio
- loosely 80 cols but 100 or more can be fine (C++ and all)

**Comment by coatless** [comment]
Replicated in RStudio with:

**Tools** -> **Global Options** -> **Code**
1. Editing - > Tab width 4
2. Display -> Show Margin -> 80

**Pull request merged**
