### PR TITLE
created src/2016-06-23-working-with-Rcpp-StringVector.Rmd

### PR DESCRIPTION
**Pull request by knausb**
In #93 I was asked to submit my contribution as a pull request instead of as a gist. This pull request includes my proposed contribution.

Thank you!
Brian

### CODE REVIEW

**Comment by eddelbuettel** [comment]
The PR currently covers 11 files, including a few older ones that should not have been committed.  Any chance you can clean that up a little?

**Comment by knausb** [comment]
Oops, I think I just learned I have a bad git habit.  I'm not sure how to handle this elegantly. So I'll close this and try a new PR. Thanks for your patience!

**Comment by eddelbuettel** [comment]
For reference, you can just `git rm someFile.abc` and then commit.

**Comment by knausb** [comment]
Ah, I'm afraid my git vocabulary is not very large. Its a little larger now. Thank you!

**Pull request closed without merging**
