### PR TITLE
Add post on RcppArrayFire

### PR DESCRIPTION
**Pull request by rstub**
c.f. #108 
I have opted to include the benchmark results directly instead of having them produced on the fly, mainly because I did not want to include the sources for the other functions.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That is a little against the spirit of everthing else we have done.  Could you try to have them self-contained with only dependencies on CRAN packages (or packages focussed in the post, here `RcppArrayFire`) ?

**Comment by rstub** [comment]
Ok, I will make it self-contained. We will need an extra iteration then since it is difficult to write about benchmarks without knowing the results :-)

**Comment by eddelbuettel** [comment]
An additional level of difficulty is of course that the results will then come from my machine ...  

I hope I won't later regret tieing myself to having this installed.

**Comment by rstub** [comment]
Maybe we should consider the "mock" option then. Do you have any "best practices" for that? I could imagine to include two flags into the Rmd file: Whether to compile and run ArrayFire code and whether to use precomputed results. Of course, if one does not use ArrayFire code one has to use the precomputed results.

**Comment by eddelbuettel** [comment]
I think it's ok for it to fail if not all requirements are installed provided the requirements are open source and _could_ be installed.

**Pull request merged**
