### PR TITLE
add initial mockup of figure support

### PR DESCRIPTION
**Pull request by olmjo**
I've got an initial mockup of figure support. I don't like it much, but it's a first cut. I'd like to hear some pushback so it can be polished.

From a contributor's perspective:
Only figures with a name prefixed by 'fig' will be written to the directory that is served, as in 

``````
 ```{r, 'fig-a-histogram'}
hist(rnorm(35))
``````

This 'fig' assumption is used in parsing the slug from the full filename. I couldn't think of something more general that didn't rely on parsing the markdown.

From knitr's perspective:
Figures are written to the same directory they have always been when knitting.

From /rcpp-gallery/Makefile's perspective:
I put a wrapper recipe around the main jekyll build. This is because in order to "work", the slug directories under `articles` must already exist. So, now there is 

```
all: knit jek img
```

Beyond that, there are definitely assumptions built in to `cp-img.sh`. E.g., I think the sed command relies on non-BSD sed and it assumes the `_site/articles/:title` structure.

So, is this a path worth continuing on? What changes would work better from your perspective?

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Wow.  Nice initiative.  Having this work would be nice.

But I can't comment much on "scope" as I know little Jekyll and how much / how badly it changes. 
@jjallaire any comments?

**Comment by olmjo** [comment]
I forgot, to successfully preview ...
- In one shell, run `make preview` and leave the server running
- In another, run `make all` which, among other things, will push the imgs to the directory being served.

**Comment by olmjo** [comment]
One flaw I thought of with this implementation is that figures are pushed to the `_site` directory from `src/figure`.  However, `_site` is re-generated from scratch each time jekyll builds. 

This means that the following order of events will create a problem:
- contributor adds src/something.Rmd which creates src/figure/fig-something.png
- the gallery is built
  - knitr generates _posts from src
  - jekyll generates _site from _posts
  - new script copies figs from src/figure
- suppose for some reason src/figure is deleted and, un-relatedly, a new contribution src/new.Rmd is added
- the gallery is built
  - knitr only generates new.md since something.md still exists, so fig-something.png isn't regenerated after the delete
  - _site is generated from _posts anew
  - the new script copies only those images from src/figure to _site.

So there will be problems is src/figure is volatile. This would not manifest if the whole gallery was built from scratch each time, but that's not a solution.

**Comment by jjallaire** [comment]
Yes, _site is generated and not checked into version control so we need to
do something out side of it. If you just put something at a top level
directory (e.g. /figures) that should certainly work though.

**Comment by olmjo** [comment]
New commits reflect a small change per @jjallaire. Went with "figure" and not "figures" to keep it identical to the knitr naming.

From my commit:

```
add figs to /figure/ first for vc checkpointing
- knit target in ./Makefile copies ./src/figure to ./figure
- img target in ./Makefile puts *.png in ./figure in the necessary
  location in _site after _site is regen-ed.

- preview target still requires "make img" after the fact to serve images
```

I vc-ed the demo imgs in ./figure/ since that looks like what the approach will be on your end of things. Of course, these will ultimately be deleted.

Thoughts?

**Comment by jjallaire** [comment]
I can't follow the whole chain on first inspection but one comment based on your description: you don't need to update _site directly (that's done automatically by jekyll). It also seems like an explicit "make img" shouldn't be necessary (i.e. why can't our knitr image hooks just get the file into the right place at the outset). Apologize if I'm missing something obvious.

**Comment by olmjo** [comment]
The explicit update to _site is me moving imgs from figure/ to the
"right" location under _site/articles/<some slug>/.

And, with my approach, I should have added figure/ to the excluded dirs
under _config.yml, but forgot about that.

That said, the image hooks may well be the right solution, I simply didn't
take the time to figure it out since this seems like a fairly non-standard
knit-ing with 3 different paths at play. But it might be easier than it
seemed  to me at first.

On Tue, Oct 14, 2014 at 3:03 PM, JJ Allaire notifications@github.com
wrote:

> I can't follow the whole chain on first inspection but one comment based
> on your description: you don't need to update _site directly (that's done
> automatically by jekyll). It also seems like an explicit "make img"
> shouldn't be necessary (i.e. why can't our knitr image hooks just get the
> file into the right place at the outset). Apologize if I'm missing
> something obvious.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jjallaire/rcpp-gallery/pull/57#issuecomment-59098348.

## 

J.P. Olmsted
j.p.olmsted@gmail.com

**Comment by jjallaire** [comment]
The point is that jekyll will do that same moving (and needs to, because
_site isn't checked into version control and is fully regenerated on the
server side by github pages). The images should go into articles/some-slug
rather than _site/articles/some-slug

**Comment by eddelbuettel** [comment]
So ... does this now work?  With just `make preview` ?  That would be so cool ...

**Comment by olmjo** [comment]
Nope. I closed it so that it might die. I've got on last idea that doesn't
involve modifying things at the knitr level. I'll see if that passes
muster, but it's sufficiently different (read simpler) that I'll submit is
a different pr.

On Tue, Oct 14, 2014 at 4:59 PM, Dirk Eddelbuettel <notifications@github.com

> wrote:
> 
> So ... does this now work? With just make preview ? That would be so cool
> ...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jjallaire/rcpp-gallery/pull/57#issuecomment-59115499.

## 

J.P. Olmsted
j.p.olmsted@gmail.com

**Pull request closed without merging**
