### PR TITLE
New post about Rcpp and R6 objects

### PR DESCRIPTION
**Pull request by dkesada**
Hello! I've created a post on how to use Rcpp to interact with R6 objects in C++. The post needs the 'R6' package to work, and I've put the 'R6' tag in the markdown, which doesn't exist at the moment. If it's too much of a hassle to create a tag just for one article, I can put some other tag related to classes, environments or object oriented programming.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thank you I will take a look over the weekend or maybe this eve.  Maybe @raphaels1 wants to take a look too...

**Comment by eddelbuettel** [comment]
@dkesada The code doesn't run for me as posted. (R 4.0.2, Rcpp 1.0.5):

```r
R> res <- initialize_list(names, ids)
Error in initialize_list(names, ids) : 
  Cannot convert object to an environment: [type=NULL; target=ENVSXP].
R> 
```

Have you encountered this?

**Comment by eddelbuettel** [comment]
I think it is because the code chunks eval independently.

**Comment by eddelbuettel** [comment]
Not having any luck either when converted to .cpp (which tends to be consumed in one piece).

**Comment by eddelbuettel** [comment]
I decided to post it 'as is' (wirth one micro editorial edit) but the R code does not show. The chunks are not connecting, and right now I do not have time to chase this, sorry.

**Comment by dkesada** [comment]
Hi! I set up a local development rcpp-gallery and managed to reproduce the error and fix it. You were right, the global environment seemed to not be storing the R6 class defined at the begining. I forced this to occur by using the scoping assignment "<<-" on the R6 class, as in your gallery example of accessing environments. Still, it's interesting that this kind of assignment is not needed in a standalone markdown or project. 

If it's ok with you, I'll fast-forward my fork and create a new pull request with this fix in place.

**Comment by eddelbuettel** [comment]
> If it's ok with you,

You didn't actually ask.  You just did.

(In code repos) we generally prefer issue tickets to discuss and form consensus prior to simply throwing PRs over the fence wild west style.  Anyway -- too late now.

Thanks for the fix, and thanks for the write-up.  It's a nice intro.

**Pull request merged**
