### PR TITLE
Update 2014-06-29-parallel-vector-sum.cpp

### PR DESCRIPTION
**Pull request by MattPD**
https://github.com/jjallaire/rcpp-gallery/issues/73

### CODE REVIEW

**Comment by jjallaire** [comment]
Note we'll still need to re-run make to have this change reflected in the published article.

**Comment by eddelbuettel** [comment]
Running it now.

**Comment by MattPD** [comment]
@jjallaire I've ran across an issue[1] with `make` (well, getting the prerequisites took a moment, too :]); so, thanks, @eddelbuettel!

Just to make sure / for the future: After running `make` I should also commit the generated `.md` file that appears in `_posts`, right? I've read the following two docs (it's not entirely clear whether that's the recommended workflow, but I deduced the `_posts` part from Dirk's commit; my lack of familiarity with Jekyll is likely to blame here):
- https://github.com/jjallaire/rcpp-gallery/wiki/Contributing-to-the-Rcpp-Gallery
- https://github.com/jjallaire/rcpp-gallery/wiki/Local-Development-Configuration

[1]: One issue was with `-lboost_python-py27` in `/src/2014-04-06-rcpp-python.Rmd`. Is hard-coding the lib version in the path required (something Debian- or Ubuntu-specific, perhaps)? On Arch Linux simply using `-lboost_python` works (there are two libraries that ship with Arch repositories, `libboost_python` and `libboost_python3`; the former corresponds to Python 2.x). Not sure how important this is, given that the article _does_ mention the "Python 2.7 from R on Ubuntu" setting, hence not opening a separate issue, but just giving a heads up about a potential speed bump on the road to automation.

**Comment by jjallaire** [comment]
At this point we don't have a lot of other folks besides Dirk and I
building the whole gallery so don't sweat it if you aren't able to build
locally (there may indeed be some distro/version specific dependencies).

**Comment by MattPD** [comment]
@jjallaire: All right!

**Comment by eddelbuettel** [comment]
Particularly that Boost Python post is gnarly.  Other ones should just work if you have Jekyll set up right.

**Comment by MattPD** [comment]
@eddelbuettel: Yup, getting the prerequisites (both OS-wide and R-specific) took most of the time, but eventually managed to get it to work, I think :-) (at least the `make preview` works; after fixing the linker flags -- by removing the aforementioned hard-coded version dependency -- that Python post seems to be building, too). It was mostly a matter of running `make`, getting a missing dependency, re-running `make`, ... :-)

**Comment by jjallaire** [comment]
For future reference there's also this script that should install
everything (at least on Debian based systems):

https://github.com/jjallaire/rcpp-gallery/blob/gh-pages/_scripts/install-dependencies-debian.sh

**Pull request merged**
