### PR TITLE
Updated armadillo subsets (closes #98)

### LINKED ISSUE #98: Updating Armadillo Subset
Possibly update the [Armadillo subset](http://gallery.rcpp.org/articles/armadillo-subsetting/) post with:
1. non-contiguous view extraction (see: http://stackoverflow.com/questions/38541787/change-elements-at-given-positions-in-an-armavec-with-corresponding-elements-i)
2. use of [sub2ind](http://arma.sourceforge.net/docs.html#sub2ind) and [ind2sub](http://arma.sourceforge.net/docs.html#ind2sub)
3. direct hints at http://arma.sourceforge.net/docs.html#submat

### PR DESCRIPTION
**Pull request by coatless**
Rewrote a large portion of the armadillo subset code with the focus on
non-continuous element access.

Though, there is a weird pygments highlighting issue that I haven’t been able to solve by how I wrote the R comments (`r_command # command does..` ) See:

screen shot 2016-07-30 at 2 28 10 am

Also, this post might want to be relabeled to be a focus on “non-continuous” views and a second post comes about dealing with “continuous” examples (e.g. `.row()`, `.col()` ).

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@jjallaire: Do you recall if the .Rmd yaml header allows for the equivalent of the `@updated` tag we now have in some of the .cpp files?   Editorially it is somewhat nice to retain 'originally written' and 'updated' tags.

**Comment by coatless** [comment]
Per a quick glance, it looks like the `@updated` tag is only valid for dates in `Mon 00, YYYY`. To have the originally written by portion, we would have to add to the yml space and update the [`_layouts/post.html`](https://github.com/RcppCore/rcpp-gallery/blob/b899e69aa54661d9434db4547a27d5c853fffd37/_layouts/post.html#L6-L11) with:

``` html
{{ page.author }} &mdash;
written {{ page.date | date: "%b %e, %Y" }} &mdash; 
{% if page.updated %} updated {{ page.updated }} &mdash; {% endif %} 
{% if page.updatedauth %} by {{ page.updatedauth }} &mdash; {% endif %} 
```

**Comment by coatless** [comment]
@eddelbuettel: So, about this update... Better off branching it as its own post?

**Comment by eddelbuettel** [comment]
I'd have to check. It may have had to do with .Rmd sources versus .cpp sources.

**Comment by eddelbuettel** [comment]
So to recap we have two or three issues here:

1) We have an updated post which has been lingering here.  Changing the entire format from cpp to Rmd was never a good idea for the start because it makes the diff monstrous.  Just how we generally don't call `clang-format` on an entire file as it would mask a short patch.   So I need to bite the bullet and _manually_ compare paragraph by paragraph.

2) We have an open question as to whether we can extend the Jekyll framework to allow for an updated tag.  That would probably be good, and it looks like you got that covered.  We could make that another PR, or just do it.  I am in favor of the latter but open to the former.

3) Can you reword your question from 9 hours ago?  What were you asking about: 1) or 2) or both?

**Comment by coatless** [comment]
1.) I was a bit more comfortable at the time writing in markdown than the cpp format. Sorry about that! If it is any consolation,  the update was a major rewrite to address the different subset views within armadillo. 
2.) That's fine. Though, should the update author be listed next the original author on the main gallery listing of all articles? (e.g. Title.... Original Author, Updated Author) Or should that be kept only within the post?
3.) Both as the update seemed to have "timed out".

**Comment by eddelbuettel** [comment]
Converting is fine.  It's that converting _when also making changes_ tends to mask the latter.

As for two: we're in a minor pickle as we allow two input formats.  Something "simple enough" and consistent between the two input formats is probably best.

**Comment by coatless** [comment]
Updated yml and minor tweaks to content

**Pull request merged**
