### PR TITLE
add data.table example

### LINKED ISSUE #125: Add example of data.table object creation
C.f. https://github.com/lsilvest/data.table_at_c_level per discussion in https://github.com/DavZim/RITCH/issues/14#issuecomment-618175746

/cc @lsilvest @DavZim

### PR DESCRIPTION
**Pull request by DavZim**
Adds an example of how to incorporate `data.table` in `Rcpp`. Closes #125

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Wicked. I owe @lsilvest a write-up / review / post on this but maybe you just did my homework for me. Will try to review in the next day or two.

**Comment by eddelbuettel** [comment]
Gave a read earlier, and it is good.  A few quick suggestions or questions or points:

- 'who': given that it draws on Leonardo's gist, shall we formally triple-author it?  Reverse alphabetical or whatever order works; @lsilvest: thoughts?

- the PR only needs the .Rmd; the rendered file gets produced anyway when I 'go to prod here'

- the top needs a little editing to avoid all the politics of data.frame derived containers; we can just say that same promoto immutable data structures yet that data.table has a different 'by-reference' design which works well for higher performance and/or large data

- the content is good; I used to have similar 'yet less polished' helper functions at work and had always hoped to take more of it 'down to C(++) level'.  I had missed the key function `setalloccol` though.  So this is good.

- Now, looking into `setalloccol` we see it makes one call to C.  We need to talk to team data.table and get that exported. _Then_ we'd be in business.  (Until then maybe 'borrow' it in a small helper/test package?)

If you want I can try to take a stab at editing and push back into your branch/repo.

**Comment by lsilvest** [comment]
I'm OK with any author order.

Concerning `setalloccol`, I'm wondering if it's not overkill to make a temporary helper/test package. It seems not that cumbersome for the time being to call `setalloccol` from R - after all, that's what the `data.table` package itself does. I can look into making a `data.table` PR for exporting that C function as I did in the past for C subsetting.

**Comment by eddelbuettel** [comment]
Agreed on possible overkill---I was not explaining myself well.  Here is a longer versions:

- medium-to-long term we want and might `data.table` to export this 
- in the meantime, we could add it to Rcpp but then Rcpp gets more depends for optional behavior
- so how a package in the middle that also allows us to test this
- we control the upload frequency so we can test
- it could contain the code we need from data.table, and a suitable header-only include to make it easy to use

All just blue sky thinking so far of course...

**Comment by DavZim** [comment]
I am also OK with any author order.
@eddelbuettel do you update the introduction to the article? Or should I rephrase it?

**Comment by eddelbuettel** [comment]
I can give it a go.

Completely forgot one more (potential) bullet point:  R 4.0.0 has a new function `list2DF()`.  Should we time it?  Or not because we do the list-to-df part in C++ anyway?

**Comment by DavZim** [comment]
I think a small section with the timings could be interesting if its not too time-consuming to create it and if the results are positive.

What I found interesting, is that the advantage of using this approach over `DataFrame` & `setDT()` is not as big as expected with largish data...

**Comment by eddelbuettel** [comment]
@lsilvest @DavZim I did a quick pass over it (and as repo co-owner can push those back to David which updates the PR).  If you have a moment, glance at it, else we can also polish once I merge.

**Comment by lsilvest** [comment]
In the intro you have:

"They also provide the basis from which two key packages extend them. One of these, the `tibble` package, operates in a similar fashion to `data.table` and treats the data as _immutable_."

In that sentence, did you mean `data.frame` rather than `data.table`?

**Comment by eddelbuettel** [comment]
Nice catch. Fixed in source.

**Pull request merged**
