### PR TITLE
add em-probit example

### PR DESCRIPTION
**Pull request by olmjo**
Wicked long pedagogical example of developing a parallel implementation of Probit regression with the EM alg. from start to finish. Intended to be accessible to a specific set of users.

It's your call if it's appropriate for the gallery or not. If not, no worries, I can put it elsewhere.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
We have no page limit _per se_ who why not?  Plus we badly need something with formulae to show off the good work of a certain @olmjo :)   

I'll merge now and will go over it later ...

**Comment by eddelbuettel** [comment]
In preview mode here, the outline formulae work but inline does not:

```
assumed to generate yi=1 if $$y_i^* \geq 0andy_i = 0otherwise.Whenweassume\epsilon_i \sim N(0, 1)$$, the
```

I just tried reducing inline $$ to $ but no luck.

Thoughts?

**Comment by eddelbuettel** [comment]
Not sure what I changed or how but it works better now... so now posted, following minor edits.

Nice work, really appreciate it!

**Comment by olmjo** [comment]
Glad it was useful and you found the issue!

Getting the fork on my laptop up and running took longer than I'd have thought.

**Comment by eddelbuettel** [comment]
Thanks again for both--the PR and the new article.

If you have pointers about how to make the setup easier / more transparent let us know...

**Pull request merged**
