### PR TITLE
RcppProgress article v1

### PR DESCRIPTION
**Pull request by kforner**
Hi,

At last the article.
Best,
Karl

### CODE REVIEW

**Comment by jjallaire** [comment]
Thanks, just merged!

J.J.

**Comment by kforner** [comment]
I think I broke evrything: the website http://gallery.rcpp.org/ do not
display the articles anymore, at least for me !

**Comment by jjallaire** [comment]
I actually think the problem is more likely to be that GitHub pages updated
to jekyll v1.0 and something broke as a result. I'll investigate further....

J

**Comment by kforner** [comment]
Ah ok

**Comment by jjallaire** [comment]
The article itself was published:

http://gallery.rcpp.org/articles/using-rcppprogress/

But the links on the homepage are broken. I'll fix this soon.

**Comment by kforner** [comment]
thx

**Comment by jjallaire** [comment]
I've updated the gallery to use jekyll 1.0 (note that this means you should
ensure your local copy is also upgraded to v1.0)

Github pages appears to be down right now but as soon as it comes back up
the site should be working again.

J.J.

**Comment by kforner** [comment]
Yes, it's working now, good !

**Pull request merged**
