### PR TITLE
New article about custom progress bars for RcppProgress

### PR DESCRIPTION
**Pull request by nevrome**
I helped @kforner to improve RcppProgress. It's now much more straight forward to implement custom progress bars. Here's a short article about this feature.

Please let me know if it fulfills the requirements of the RcppGallery.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
As a new article, or should it be an edit / extension / update of the existing one dated 2003-05-16 ?

**Comment by nevrome** [comment]
This is a new article.

**Comment by eddelbuettel** [comment]
I know it is. I am asking you if you would consider updating the old article instead?

**Comment by nevrome** [comment]
I believe the two articles cover different topics and address users in different situations: The new one doesn't render the old one useless. Also both are already quite lengthy: Combining both would make them less accessible.

Would you prefer to have them merged anyway? You know the gallery much better than I do. I also have to ask @kforner about his opinion.

**Comment by eddelbuettel** [comment]
Sounds fine.  Let me take a look later and maybe just merge.  Did you manage to render it, ie it all works?  I sometimes just edit in a minor way for consistence across posts.

**Comment by nevrome** [comment]
Thanks for your time! Let me know, if you find something that should be improved. I've still a lot to learn. 

The article can be knitted successfully in RStudio. I tried to incorporate the hints on the *Contributing to the Rcpp Gallery* page, but I didn't create a Local-Development-Configuration.

**Comment by eddelbuettel** [comment]
Ok, I'll pull it locally first and test.

**Comment by eddelbuettel** [comment]
This does not seem ready:

image

**Comment by eddelbuettel** [comment]
But easy enough to fix so I'll just do the cleanup.

**Comment by nevrome** [comment]
Thanks a lot for the reformatting!

**Pull request merged**
