### PR TITLE
Added post: Call matplotlib from R with Rcpp

### PR DESCRIPTION
**Pull request by mpastell**
Added a post about calling matplotlib from R.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Awesome. I'll merge this now and may make one editorial pass over it which includes (re-)building on my Ubuntu box.

**Comment by eddelbuettel** [comment]
Now posted with very minimal edits.  Thanks again!

(And if there is a way to add a static graph from matplotlib maybe we should, as at least "now we can" ;-)

**Comment by mpastell** [comment]
You're welcome. Thanks for the quick edit and all the work on Rcpp. You can save a figure by calling:

``` r
 pyrun("plt.savefig('pyplot.png')")
```

I can add it if you want, where should it be saved and whats the correct include path for markdown?

**Comment by eddelbuettel** [comment]
Can you try locally?  I am currently on away from home and work.   

One of the most recent posts introduces images and plots.  We can probably retrace what it does.  Just calling plot is _probably_ good enough.   Worst case it can wait til next week -- or maybe I'll try too.

**Comment by mpastell** [comment]
I'll try. I think I was able to figure out how its done in http://gallery.rcpp.org/articles/SIR-and-revolution/. 

UPDATE: I found the correct setup from knit.sh

``` r
 knitr::opts_chunk$set(cache.path=file.path('cache', prefix),
                        fig.path=file.path('../figure', prefix))
```

**Pull request merged**
