### PR TITLE
Example to recreate the base R behavior of rmultinom and rpois with Rcpp functions.

### PR DESCRIPTION
**Pull request by jfrench**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Will take a closer look.  But from 10,000 feet, if `rmultinom` and `rpois` are not doing what the R functions do, is there a case for fixing the sugar functions?

**Comment by jfrench** [comment]
Hi Dirk,

Based on what I was trying to do:

1. The sugar version of rmultinom only returns a single vector of
multinomial outcomes. The base R version allows you to return n of these
vectors simultaneously (as a k x n matrix, where k is the number of
outcomes and n is the number of simulated data sets).
2. The sugar version of rpois seems to only take a single value of lambda
(the distribution mean), whereas the R version allows a vector.

At least for the sugar version of rpois, this code should reproduce the
problem:

```r
src2 = '
#include <Rcpp.h>
using namespace Rcpp;

IntegerVector rpois2(unsigned int n, NumericVector lambda) {
  return Rcpp::rpois(n, lambda);
}
'
Rcpp::sourceCpp(code = src2)
rpois2(10, 1:2)
```

This will produce an error. The relevant part is:

initializing argument 2 of 'Rcpp::NumericVector Rcpp::rpois(int, double)'
 inline NumericVector rpois( int n, double mu ){


I won't comment on whether the sugar functions should be "fixed". They
don't directly seem to mimic the base R functionality (at least in these
cases), but perhaps that's okay. And I'm not sure how difficult backwards
compatibility would be.

Best,

Joshua

**Comment by eddelbuettel** [comment]
Yep, I think I looked into that many moons ago for `rmultinom` and may also have seen the scalar vs vector issue.  Not everything maps one to one and we have eg three variants for some.  Ie here is `rnorm()` via `R::`, via the basic Rcpp function and via the vectorized sugar function:

```r
R> Rcpp::cppFunction("double f1() { return R::rnorm(0,1); }")
R> set.seed(42); rnorm(1)
[1] 1.37096
R> set.seed(42); f1()
[1] 1.37096
R> Rcpp::cppFunction("NumericVector f2() { return Rcpp::rnorm(1); }")
R> set.seed(42); f2()
[1] 1.37096
R> 
```

**Comment by eddelbuettel** [comment]
I didn't pay attention to the file -- you had by mistake in `_posts` and not in `src/` and now Jekyll is confused and does not show it.

[ A little later. ]

Now fixed.

**Pull request merged**
