### PR TITLE
Fix bug in plyr conversion example. Closes #66

### LINKED ISSUE #66: Possible bug in example split_indices function
While reading through [_posts/2013-12-02-plyr-c-to-rcpp.md](http://gallery.rcpp.org/articles/plyr-c-to-rcpp/) trying to make sense of the C++ code and the intended output of the `split_indices` function, I may have found a small bug.  I ended up running the function to get an idea of the output it generated and was surprised by the result.

Currently, it appears that unless the `IntegerVector x` passed into the function is presorted from min to max, or `n = max(x)`, then the list returned by the function is truncated by `ids.resize(x[i])` to a length that is the value of the final element of `x`. For example, `split_indices(sample(100))` typically results in lists that are less than 100 elements long despite no replacement, whereas `split_indices(sample(100), n = 100)` returns the value I would expect.

I'm not really sure what the intended output is supposed to be, but rather than:

```
if (x[i] > n) {
    ids.resize(x[i]);
 }
```

perhaps the code should be:

```
if (x[i] > ids.size()) {
    ids.resize(x[i]);
}
```

Then the length of `ids` will only be extended via `resize` rather than possibly truncated in the situation where `x[i] > n` but `x[i] < ids.size()`.

Additionally, there are two references to `out` in the second bullet point under the example C++ code which should probably be changed to `ids`.

Thanks

### PR DESCRIPTION
**Pull request by hadley**
Included small note about bug in text. 

I re-made locally to generate the md file.

### CODE REVIEW

**Comment by jjallaire** [comment]
Thanks! You should remove the .md though as Rcpp Gallery uses a special markdown conversion process (since it targets Jekyll it needs to use Jekyll code blocks rather than traditional GitHub code blocks).

**Comment by hadley** [comment]
@jjallaire done - I assumed since `make` made that file it would be generated correctly.

**Comment by jjallaire** [comment]
Oops, I see the problem now. You did do it correctly (via make) however it looks like you switched the C++ code chunk to be non executable within the Rmd (which caused the generated .md to no longer use jekyll code chunks). Was it your intention to make it non-executable? BTW I can take this PR from here.... (I'll switch it back to executable and regenerate the .md via make)

**Comment by hadley** [comment]
Yes - I couldn't get it to build, and the build errors were beyond my ability to diagnose (and it didn't seem that important to build it, given that I don't actually execute the code)

**Comment by jjallaire** [comment]
Interesting. I got it to build on my config (on Linux, perhaps there's an issue on the Mac). Anyway, has been merged and all is well.

**Pull request merged**
