### PR TITLE
Fast Multivariate Normal Densities with RcppArmadillo and openMP

### PR DESCRIPTION
**Pull request by ninohardt**
Submission based on SO thread:
http://stackoverflow.com/questions/17617618/dmvnorm-mvn-density-rcpparmadillo-implementation-slower-than-r-package-includi

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Hm, I thought I had commented on this earlier. Trying again...

Quick ones:
- Please remove the intro paragraph. No other Gallery posts discusses installation, this is inappropriate.
- Please do not add extra tags (ie remove MNV), spell consistently (we used 'openmp')
- A bit more motivation in the text would be good.
- A bit more comparison to the previous post by dickoa on multivariate Normal draws would be nice.
- Instead of arma::datum::pi you can also use M_PI from the standard math headers

Dirk

**Comment by eddelbuettel** [comment]
Also, standard 4 space indentation would be appreciated for the code.

**Comment by eddelbuettel** [comment]
Nice, much better. In open text it should be 'Open MP', but I can also do that by hand later. Will get to this this evening I hope.

**Comment by jacsor** [comment]
I think there is an error in the code. The line:

```
double constants = -(xdim/2) * log2pi;
```

should be 

```
double constants = -((double)xdim/2) * log2pi;
```

**Comment by eddelbuettel** [comment]
I think you are right.  Another way would be

```
double constants = -(xdim/2.0) * log2pi;
```

**Comment by dickoa** [comment]
Thanks for catching this error.

**Comment by eddelbuettel** [comment]
I committed a more explicit `static_cast<double>(xdim)`. Thanks.

**Pull request merged**
