### PR TITLE
Support MathJax conditionally

### PR DESCRIPTION
**Pull request by olmjo**
Added conditional MJ support with rendering from cdn.mathjax.org.
- MathJax script included in "head" tag of HTML **iff** "mj" frontmatter tag is "true" (without quotes) as in

```

---
title: something
mj: true

---
```
- MathJax support is undetectable (I think) in posts without the mj tag.
- Added (to-be-trashed) example post to demo. 
- Both inline and display math are supported and determined by the markup generator.

Caveat: the diff shows that I killed some extra whitespace, sorry :-(

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Very interesting! 

I'll let JJ chime in as he is the master of all things Jekyll here, but thanks for getting us this far!

**Comment by olmjo** [comment]
In looking at an old issue it looks like there were some headaches with trying MJ support in the past. I'm not sure what the ultimate cause of that was.

But I tested with jekyll 2.4-0 (but that shouldn't matter, I don't think) and kramdown 1.4.2 (which could matter).

No evidence of a headache on my end and **no** HTML markup req'd in the R markdown.

**Comment by olmjo** [comment]
And, since gh provides, might as well drag and drop an image:
screen shot 2014-09-30 at 10 38 37 pm

**Comment by jjallaire** [comment]
The big issue with MathJax is preventing the markdown processor from getting it's hands on the embedded math (i.e. processing markdown within math). This doesn't happen in all cases but it happens enough for it to be a practical concern. If this PR could deal with that issue in some fashion it would be a slam dunk. If we can't deal with that we'd have to take this eyes wide open knowing that we only support a subset of LaTeX math. BTW one possibility is simply using markdown escaping via \ within the math. If that's a legit option with this markdown back-end let us know.

I'd also like to see the YAML field be named "mathjax" for improved clarity.

**Comment by olmjo** [comment]
- field changed to "mathjax"
- added config to tell mathjax to render only what comes out of kramdown as math
- still looking into the kramdown processing markdown within math

**Comment by olmjo** [comment]
The one (known) issue I have seen that isn't fixed in the current kramdown version is mistaken generation of tables in inline math chunks. This doesn't affect display blocks and the kramdown-suggested work around is to just use "\vert" and not "|"  (http://kramdown.gettalong.org/syntax.html).

Other than that, I couldn't find reference to other issues or induce any myself.

Is that one limitation (i.e., use \vert in inline math chunks) prohibitively headachey from your perspective?

**Comment by jjallaire** [comment]
Just merged. I'm going to remove the example Rmd file just to make sure we don't publish it by mistake.

**Comment by eddelbuettel** [comment]
+1 and +1

**Pull request merged**
